### PR TITLE
download_media

### PR DESCRIPTION
**Pull request by xarthna**
Add a download route to tell clients to start immediate download instead of display

### CODE REVIEW

**Comment by xarthna** [comment]
@DrBoolean @adambaker @begriffs Wanted to have this pulled in, instead of pushing to master. Wanted to start discussion if this is something we should be supporting, and if so, make sure we are doing it correctly.  Browser clients can issue this request to force an immediate download instead of displaying the media in browser.

**Comment by adambaker** [comment]
Does this actually attach the file to the body of the request?

**Comment by DrBoolean** [comment]
I see the use case here and I think the code is sound. I'd like nginx to serve static assets directly, but I don't think it can set the Content-Disposition.

**Comment by xarthna** [comment]
@adambaker This doesn't attach a file to the body in the response. The GET request gets a response header content-disposition: 'attachment', that is supposed to instruct the user-agent to invoke its save as utility. Im looking at [rfc6266](http://tools.ietf.org/html/rfc6266) for reference. But as of now, I don't think this is working correctly since it is empty response. It needs to save as with correct path.

@DrBoolean I think we may be able to set headers in nginx to do so after looking at the reverse proxy stuff in the documents last week, but will have to look more to confirm.

**Comment by adambaker** [comment]
Right, but if you don't append the file to the response body, won't the user just end up saving an empty file?

**Comment by xarthna** [comment]
@adambaker Thats exactly whats happening now. I need to update the PR.

**Comment by begriffs** [comment]
Under what conditions do you want to set the `Content-Disposition` header? One way to do it would be to write a middleware function to layer on top of wai-middleware-static that would decorate the responses of any GET request.

**Comment by adambaker** [comment]
Joe has a good point; that's probably a better way of implementing this.

Taking a further step back: I don't like this feature. If I have my browser configured to do something with certain file types other than prompt me to save them, that's what I want it to do. I don't like it when sites override my decision on that. Also, if it displays the media in browser, the user can always hit Ctrl-S and save it.

Then again, I understand that I'm competent with a web browser, and we're making this for people who might not be.

**Comment by xarthna** [comment]
Joe does bring up a good point.

If everyone agrees with Adam , we can back off of this, because the way he described the functionality is the current way things are implemented.

If we want to press forward, we can talk further about implementation details in office next week.

**Pull request closed without merging**
